/*
 * AI model Service Restful API
 * This is an ai model service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aliyun.openservices.aiservice.api;

import com.aliyun.openservices.aiservice.ApiClient;
import com.aliyun.openservices.aiservice.model.AsyncJobResponse;
import com.aliyun.openservices.aiservice.model.AsyncVideoBatchJobResponse;
import com.aliyun.openservices.aiservice.model.AsyncVideoJobResponse;
import com.aliyun.openservices.aiservice.model.BatchVideoRequest;
import com.aliyun.openservices.aiservice.model.Response;
import com.aliyun.openservices.aiservice.model.VideoMeta;
import com.aliyun.openservices.aiservice.model.VideoRequest;
import org.junit.Before;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * API tests for AiServiceVideoApi
 */
@Ignore
public class AiServiceVideoApiTest {

    private  AiServiceVideoApi api ;


    @Before
    public void createApi() {
        String host  = Constants.host;
        String appId = Constants.appId;
        String token = Constants.token;
        ApiClient apiClient = new ApiClient(host, appId, token);
        api = new AiServiceVideoApi(apiClient);
    }

    /**
     * 视频多模态接口
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void multiModalClassifyTest() throws Exception {
        String videoUrl = "http://v1.keepcdn.com/tweet-entry-video/5f9eaf52d9e7c4253a50f3d8/2023/08/28/59f9ff9f-9eea-42a2-a6f2-b352fb31d956/169317149931964ebbf2bcd76560001b6a3f0.mp4";
        List<String> images = Arrays.asList();

        String text = "标题: 胜利公园晨跑打卡。 内容: ";
        AsyncVideoJobResponse response = api.multiModalClassify(videoUrl, images, text);

        System.out.println(response);
        System.out.println(response.getJobId());
    }

    /**
     * 视频检测接口
     *
     *
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void classifyLabelVideoTest() throws Exception {
        String videoUrl = "https://ocr-alt.oss-cn-zhangjiakou.aliyuncs.com/uc_video/2881191243992322456.mp4";
        String title = "2881191243992322456";
        AsyncVideoJobResponse response = api.classifyLabelVideo(videoUrl, title);

        System.out.println(response);
        System.out.println(response.getJobId());
    }

    /**
     * 批量视频检测接口
     *
     *
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void batchClassifyLabelVideoTest() throws Exception {
        List<VideoMeta> videos = new ArrayList<>();
        videos.add(new VideoMeta().url("https://ocr-alt.oss-cn-zhangjiakou.aliyuncs.com/uc_video/2881191243992322456.mp4").title("test"));
        videos.add(new VideoMeta().url("https://ocr-alt.oss-cn-zhangjiakou.aliyuncs.com/uc_video/2881191243992322456.mp4").title("test"));

        AsyncVideoBatchJobResponse response = api.batchClassifyLabelVideo(videos, "", null);

        System.out.println(response);
        System.out.println(response.getBatchJobId());
    }

    /**
     * 视频质量接口
     *
     *
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void videoQATest() throws Exception {
        String videoUrl = "https://ocr-alt.oss-cn-zhangjiakou.aliyuncs.com/uc_video/2881191243992322456.mp4";
        String title = "2881191243992322456";
        AsyncVideoJobResponse response = api.videoQA(videoUrl, title);

        System.out.println(response);
        System.out.println(response.getJobId());
    }
}
