/*
 * AI model Service Restful API
 * This is an ai model service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aliyun.openservices.aiservice.api;

import com.aliyun.openservices.aiservice.model.AICreationRequest;
import com.aliyun.openservices.aiservice.model.Response;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for AiServiceAiCreationApi
 */
@Ignore
public class AiServiceAiCreationApiTest {

    private final AiServiceAiCreationApi api = new AiServiceAiCreationApi();

    /**
     * AI创作接口
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void aiCreationTest() throws Exception {
        AICreationRequest body = null;
        Response response = api.aiCreation(body);

        // TODO: test validations
    }
}
