/*
 * AI model Service Restful API
 * This is an ai model service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aliyun.openservices.aiservice.api;

import com.aliyun.openservices.aiservice.ApiClient;
import com.aliyun.openservices.aiservice.model.ImageRequest;
import com.aliyun.openservices.aiservice.model.Response;
import org.junit.Before;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for AiServiceImageApi
 */
@Ignore
public class AiServiceImageApiTest {

    private  AiServiceImageApi api ;

    @Before
    public void createApi() {
        String host  = Constants.host;
        String appId = Constants.appId;
        String token = Constants.token;
        ApiClient apiClient = new ApiClient(host, appId, token);
        api = new AiServiceImageApi(apiClient);
    }
    /**
     * 人脸属性分析
     *
     *
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void faceAttrImageTest() throws Exception {
        String image = "https://pai-rec-public.oss-cn-shanghai.aliyuncs.com/ai-service/demo/face_chenglong.png";
        Response response = api.faceAttrImage(image);

        System.out.println(response);
    }

    /**
     * 图像打标
     *
     *
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void multiLabelImageV2Test() throws Exception {
        String image = "https://pai-rec-public.oss-cn-shanghai.aliyuncs.com/ai-service/demo/face_chenglong.png";
        Response response = api.multiLabelImageV2(image, "", null);

        System.out.println(response);
    }
    /**
     * 图片检测接口
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void aiModelImageTest() throws Exception {
        ImageRequest body = null;
        Response response = api.aiModelImage(body);

        // TODO: test validations
    }
}
