/*
 * AI model Service Restful API
 * This is an ai model service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aliyun.openservices.aiservice.api;

import com.aliyun.openservices.aiservice.model.ImageWithTextRequest;
import com.aliyun.openservices.aiservice.model.Response;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for AiServiceImageTextApi
 */
@Ignore
public class AiServiceImageTextApiTest {

    private final AiServiceImageTextApi api = new AiServiceImageTextApi();

    /**
     * 图片检测接口
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void aiModelImageWithTextTest() throws Exception {
        ImageWithTextRequest body = null;
        Response response = api.aiModelImageWithText(body);

        // TODO: test validations
    }
}
