/*
 * AI model Service Restful API
 * This is an ai model service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aliyun.openservices.aiservice.api;

import com.aliyun.openservices.aiservice.ApiClient;
import com.aliyun.openservices.aiservice.model.AsyncBatchJobData;
import com.aliyun.openservices.aiservice.model.AsyncBatchJobResponse;
import com.aliyun.openservices.aiservice.model.AsyncJobResponse;
import com.aliyun.openservices.aiservice.model.AsyncJobState;
import com.aliyun.openservices.aiservice.model.Response;
import org.junit.Before;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for AiServiceJobApi
 */
@Ignore
public class AiServiceJobApiTest {

    private  AiServiceJobApi api ;

    @Before
    public void createApi() {
        String host  = Constants.host;
        String appId = Constants.appId;
        String token = Constants.token;
        ApiClient apiClient = new ApiClient(host, appId, token);
        api = new AiServiceJobApi(apiClient);
    }
    /**
     * 根据 jobid 查询异步任务
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAsyncJobTest() throws Exception {
        Integer jobId = 12187;
        AsyncJobResponse response = api.getAsyncJob(jobId);

        if (response.getData().get("job").getState() == AsyncJobState.JOB_STATE_WAIT) {
            System.out.println("job running");
        } else if (response.getData().get("job").getState() == AsyncJobState.JOB_STATE_SUCCESS) {
            System.out.println("job success");
            System.out.println(response);
            System.out.println(response.getData().get("job"));
        } else {
            System.out.println("job fail");
            System.out.println(response);
        }
    }
    /**
     * 根据 batch id 查询异步任务
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getBatchJobTest() throws Exception {
        Integer batchId = 1965;
        AsyncBatchJobResponse response = api.getBatchJob(batchId);

        System.out.println(response);
        for (AsyncBatchJobData data : response.getBatchJobs()) {
            System.out.println(data);
        }
    }
}
