/*
 * AI model Service Restful API
 * This is an ai model service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aliyun.openservices.aiservice.api;

import com.aliyun.openservices.aiservice.model.Response;
import com.aliyun.openservices.aiservice.model.TextRequest;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for AiServiceTextApi
 */
@Ignore
public class AiServiceTextApiTest {

    private final AiServiceTextApi api = new AiServiceTextApi();

    /**
     * 文本检测接口
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void aiModelTextTest() throws Exception {
        TextRequest body = null;
        Response response = api.aiModelText(body);

        // TODO: test validations
    }
}
