/*
 * AI model Service Restful API
 * This is an ai model service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aliyun.openservices.aiservice.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * AIGCCreatRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-09-01T11:22:49.224499673Z[GMT]")

public class AIGCCreatRequest {
  @SerializedName("action")
  private String action = null;

  @SerializedName("model_id")
  private String modelId = null;

  @SerializedName("model_ids")
  private String[] modelIds = null;

  @SerializedName("model_name")
  private String modelName = null;

  @SerializedName("template_image")
  private String templateImage = null;

  @SerializedName("configure")
  private Object configure = null;

  public AIGCCreatRequest action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @Schema(example = "AIGCImageCreate", required = true, description = "")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public AIGCCreatRequest modelId(String modelId) {
    this.modelId = modelId;
    return this;
  }

  public AIGCCreatRequest modelIds(String[] modelIds) {
    this.modelIds = modelIds;
    return this;
  }

   /**
   * Get modelId
   * @return modelId
  **/
  @Schema(example = "yangmi", required = true, description = "")
  public String getModelId() {
    return modelId;
  }

  public String[] getModelIds() {
    return modelIds;
  }

  public void setModelId(String modelId) {
    this.modelId = modelId;
  }

  public void setModelIds(String[] modelIds) {
    this.modelIds = modelIds;
  }

  public AIGCCreatRequest modelName(String modelName) {
    this.modelName = modelName;
    return this;
  }

   /**
   * Get modelName
   * @return modelName
  **/
  @Schema(description = "")
  public String getModelName() {
    return modelName;
  }

  public void setModelName(String modelName) {
    this.modelName = modelName;
  }

  public AIGCCreatRequest templateImage(String templateImage) {
    this.templateImage = templateImage;
    return this;
  }

   /**
   * Get templateImage
   * @return templateImage
  **/
  @Schema(example = "http:xxx", description = "")
  public String getTemplateImage() {
    return templateImage;
  }

  public void setTemplateImage(String templateImage) {
    this.templateImage = templateImage;
  }

  public AIGCCreatRequest configure(Object configure) {
    this.configure = configure;
    return this;
  }

   /**
   * Get configure
   * @return configure
  **/
  @Schema(description = "")
  public Object getConfigure() {
    return configure;
  }

  public void setConfigure(Object configure) {
    this.configure = configure;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AIGCCreatRequest aiGCCreatRequest = (AIGCCreatRequest) o;
    return Objects.equals(this.action, aiGCCreatRequest.action) &&
        Objects.equals(this.modelId, aiGCCreatRequest.modelId) &&
        Objects.equals(this.modelIds, aiGCCreatRequest.modelIds) &&
        Objects.equals(this.modelName, aiGCCreatRequest.modelName) &&
        Objects.equals(this.templateImage, aiGCCreatRequest.templateImage) &&
        Objects.equals(this.configure, aiGCCreatRequest.configure);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, modelId, modelIds, modelName, templateImage, configure);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AIGCCreatRequest {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    modelId: ").append(toIndentedString(modelId)).append("\n");
    sb.append("    modelIds: ").append(toIndentedString(modelIds)).append("\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    templateImage: ").append(toIndentedString(templateImage)).append("\n");
    sb.append("    configure: ").append(toIndentedString(configure)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
