/*
 * AI model Service Restful API
 * This is an ai model service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aliyun.openservices.aiservice.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * LLMEvalJudgerRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-01T14:03:01.774046028Z[GMT]")

public class LLMEvalJudgerRequest {
  @SerializedName("action")
  private String action = null;

  @SerializedName("model_name")
  private String modelName = null;

  @SerializedName("model")
  private String model = null;

  @SerializedName("messages")
  private List<LLMEvalJudgerRequestMessages> messages = new ArrayList<LLMEvalJudgerRequestMessages>();

  public LLMEvalJudgerRequest action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @Schema(example = "LLMEvalJudger", required = true, description = "")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public LLMEvalJudgerRequest modelName(String modelName) {
    this.modelName = modelName;
    return this;
  }

   /**
   * Get modelName
   * @return modelName
  **/
  @Schema(description = "")
  public String getModelName() {
    return modelName;
  }

  public void setModelName(String modelName) {
    this.modelName = modelName;
  }

  public LLMEvalJudgerRequest model(String model) {
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @Schema(example = "Themis-1.0", required = true, description = "")
  public String getModel() {
    return model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public LLMEvalJudgerRequest messages(List<LLMEvalJudgerRequestMessages> messages) {
    this.messages = messages;
    return this;
  }

  public LLMEvalJudgerRequest addMessagesItem(LLMEvalJudgerRequestMessages messagesItem) {
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * Get messages
   * @return messages
  **/
  @Schema(required = true, description = "")
  public List<LLMEvalJudgerRequestMessages> getMessages() {
    return messages;
  }

  public void setMessages(List<LLMEvalJudgerRequestMessages> messages) {
    this.messages = messages;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LLMEvalJudgerRequest llMEvalJudgerRequest = (LLMEvalJudgerRequest) o;
    return Objects.equals(this.action, llMEvalJudgerRequest.action) &&
        Objects.equals(this.modelName, llMEvalJudgerRequest.modelName) &&
        Objects.equals(this.model, llMEvalJudgerRequest.model) &&
        Objects.equals(this.messages, llMEvalJudgerRequest.messages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, modelName, model, messages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LLMEvalJudgerRequest {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
