/*
 * AI model Service Restful API
 * This is an ai model service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aliyun.openservices.aiservice.api;

import com.aliyun.openservices.aiservice.model.ImageRequest;
import com.aliyun.openservices.aiservice.model.Response;
import com.aliyun.openservices.aiservice.ApiCallback;
import com.aliyun.openservices.aiservice.ApiClient;
import com.aliyun.openservices.aiservice.ApiException;
import com.aliyun.openservices.aiservice.ApiResponse;
import com.aliyun.openservices.aiservice.Configuration;
import com.aliyun.openservices.aiservice.Pair;
import com.aliyun.openservices.aiservice.ProgressRequestBody;
import com.aliyun.openservices.aiservice.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AiServiceImageApi {
    private ApiClient apiClient;

    public AiServiceImageApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AiServiceImageApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for aiModelImage
     * @param body 图片检测body (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call aiModelImageCall(ImageRequest body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = body;
        
        // create path and map variables
        String localVarPath = "/api/v1/images";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "auth", "requestTime" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aiModelImageValidateBeforeCall(ImageRequest body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling aiModelImage(Async)");
        }
        
        com.squareup.okhttp.Call call = aiModelImageCall(body, progressListener, progressRequestListener);
        return call;
    }

    /**
     * 人脸属性分析
     *
     * @param image 图片地址，url or base64 encode image (required)
     *
     * @return Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Response faceAttrImage(String image) throws ApiException {
        return faceAttrImage(image, "", null);
    }

    /**
     * 人脸属性分析
     *
     * @param image 图片地址，url or base64 encode image (required)
     * @param modelName 模型名称
     * @param config 模型配置
     *
     * @return Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Response faceAttrImage(String image, String modelName, Map<String, Object> config) throws ApiException {
        ImageRequest body = new ImageRequest();
        body.setAction("FaceAttrImage");
        body.setConfigure(config);
        body.setImage(image);
        body.setModelName(modelName);
        ApiResponse<Response> resp = aiModelImageWithHttpInfo(body);
        return resp.getData();
    }
    /**
     * 图像打标
     *
     * @param image 图片地址，url or base64 encode image (required)
     *
     * @return Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Response multiLabelImageV2(String image) throws ApiException {
        return multiLabelImageV2(image, "", null);
    }

    /**
     * 图像打标
     *
     * @param image 图片地址，url or base64 encode image (required)
     * @param modelName 模型名称
     * @param config 模型配置
     *
     * @return Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Response multiLabelImageV2(String image, String modelName, Map<String, Object> config) throws ApiException {
        ImageRequest body = new ImageRequest();
        body.setAction("MultiLabelImageV2");
        body.setConfigure(config);
        body.setImage(image);
        body.setModelName(modelName);
        ApiResponse<Response> resp = aiModelImageWithHttpInfo(body);
        return resp.getData();
    }

    /**
     * 图像质量评分
     *
     * @param image 图片地址，url or base64 encode image (required)
     *
     * @return Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Response imageQA(String image) throws ApiException {
        return imageQA(image, "", null);
    }

    /**
     * 图像质量评分
     *
     * @param image 图片地址，url or base64 encode image (required)
     * @param modelName 模型名称
     * @param config 模型配置
     *
     * @return Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Response imageQA(String image, String modelName, Map<String, Object> config) throws ApiException {
        ImageRequest body = new ImageRequest();
        body.setAction("ImageQA");
        body.setConfigure(config);
        body.setImage(image);
        body.setModelName(modelName);
        ApiResponse<Response> resp = aiModelImageWithHttpInfo(body);
        return resp.getData();
    }

    /**
     * 图片检测接口
     * 
     * @param body 图片检测body (required)
     * @return Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Response aiModelImage(ImageRequest body) throws ApiException {
        ApiResponse<Response> resp = aiModelImageWithHttpInfo(body);
        return resp.getData();
    }

    /**
     * 图片检测接口
     * 
     * @param body 图片检测body (required)
     * @return ApiResponse&lt;Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Response> aiModelImageWithHttpInfo(ImageRequest body) throws ApiException {
        com.squareup.okhttp.Call call = aiModelImageValidateBeforeCall(body, null, null);
        Type localVarReturnType = new TypeToken<Response>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * 图片检测接口 (asynchronously)
     * 
     * @param body 图片检测body (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aiModelImageAsync(ImageRequest body, final ApiCallback<Response> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aiModelImageValidateBeforeCall(body, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Response>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
